# Generated by Django 4.1.1 on 2022-09-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='book_inst',
            field=models.ManyToManyField(to='stock.bookinstance'),
        ),
    ]
