# Generated by Django 4.1.1 on 2022-09-29 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_order_change_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='change_status',
            field=models.BooleanField(default=False, verbose_name='Обновить книги'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='stock.order'),
        ),
    ]
