# Generated by Django 4.1.1 on 2022-09-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_work', 'В работе'), ('success', 'Успешно отправлен'), ('fail', 'Не отправлен')], default='in_work', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
