# Generated by Django 4.1.1 on 2022-10-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.IntegerField(null=True, verbose_name='Индекс'),
        ),
    ]
