# Generated by Django 4.1.1 on 2022-10-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_book_book_id_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity_in_stock',
            field=models.IntegerField(null=True, verbose_name='Количество книг на складе'),
        ),
    ]
