# Generated by Django 4.1.1 on 2022-09-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinstance',
            managers=[
            ],
        ),
    ]
